Python 복습

In [119]:
# Markdown 수식 작성
# $$
#     \begin{pmatrix}
#     1&2&3\\
#     4&5&6\\
#     \end{pmatrix}
# $$

# Markdown 수식 작성
$$
    \begin{pmatrix}
    1&2&3\\
    4&5&6\\
    \end{pmatrix}
$$

# Markdown 수식 작성 -latex 태그로 작성 가능
$$
    \begin{pmatrix}
    1&2&3\\
    4&5&6\\
    \end{pmatrix}
    +
    \begin{pmatrix}
    5&5&5\\
    5&5&5\\
    \end{pmatrix}
$$

$$
    \begin{pmatrix}
    1&2&3\\
    4&5&6\\
    \end{pmatrix}
    \times
    \begin{pmatrix}
    5&5&5\\
    5&5&5\\
    \end{pmatrix}
$$

$$
    \begin{pmatrix}
    1&2&3\\
    4&5&6\\
    \end{pmatrix}
    \times
    \begin{pmatrix}
    5&5\\
    5&5\\
    5&5\\
    \end{pmatrix}
$$

# Numpy
- 데이터는 행렬로 표현(영상도 포함)
- 선행대수/ 통계 연산을 위한 라이브러리

pandas: 데이터 분석에 가장 많이 활용\
numpy: 알고리즘 활용에 numpy가 필수적 패키지

In [120]:
import numpy as np

In [121]:
# array broadcasting
# 차원이 다른 연산을 동일한 차원으로 자동으로 변경시켜 연산을 가능하게 해주는 것
# 딥러닝에서 bias(편향) 계산을 할 때 주로 사용

In [122]:
ary = np.array(np.random.randint(10))
ary

array(7)

In [123]:
ary = np.array(np.random.randint(10,100,10))
ary

array([69, 47, 80, 50, 83, 94, 11, 79, 60, 35])

In [124]:
# 초기 가중치 생성
ary = np.array(np.random.randn(10)) #표준정규분포를 따르는 난수 생성 - 초기 가중치 생성 때 사용
ary

array([-0.01018105, -0.49702099, -0.34986843, -1.30631738, -0.88002389,
        1.08772986,  0.46679127,  0.66046937, -1.38182342, -0.45527708])

In [125]:
# 편향값 생성
bias=np.random.rand(1)
bias

array([0.08903599])

In [126]:
ary + bias  #array broadcasting

array([ 0.07885494, -0.40798501, -0.26083244, -1.21728139, -0.7909879 ,
        1.17676585,  0.55582726,  0.74950536, -1.29278743, -0.3662411 ])

통계함수
- max, min, mean, median, var, std

In [127]:
np.max(ary), np.min(ary)  #min, max normalization때 사용-> 데이터 정규화 때

(1.0877298621156508, -1.3818234204275799)

Random 모듈
- seed: 랜덤 모듈의 규칙값, 난수 생성 환경 고정
- randint: 균등분포로 정수 생성
- randn: 정규분포로 난수 생성
- shuffle: 무작위 섞기
- choice: 특정확률로 데이터 뽑기

In [128]:
seed = 603  # 머신러닝 딥러닝에서 하이퍼파라미터로 사용

np.random.seed(seed)
r1 = np.random.rand(10)

np.random.seed(1)
r2 = np.random.rand(10)

np.random.seed(seed)
r3 = np.random.rand(10)

In [129]:
r1, r2, r3

(array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]),
 array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
        3.96767474e-01, 5.38816734e-01]),
 array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]))

In [130]:
# 머신러닝 예시
# scaling 처리 후 return 값으로 ndarray 타입 데이터로 출력

In [131]:
from sklearn.preprocessing import MinMaxScaler # 입력된 값을 정규화 하는 것 ->  scaling
import pandas as pd

In [132]:
x= np.random.randint(1,100,10).reshape(-1,2) #5행 2열 데이터 생성
df = pd.DataFrame(x)

df

0   1
0  94  21
1  49  93
2   5  96
3  29  83
4  77  45

In [133]:
scaled_data = MinMaxScaler().fit_transform(df)
scaled_data, type(scaled_data)

(array([[1.        , 0.        ],
        [0.49438202, 0.96      ],
        [0.        , 1.        ],
        [0.26966292, 0.82666667],
        [0.80898876, 0.32      ]]),
 numpy.ndarray)

In [134]:
zero_ary = np.zeros((4,4))
zero_ary

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [137]:
w = np.random.randn(4)
shp = np.zeros((4,4))

for i in range(shp.shape[0]):
    for j in range(shp.shape[1]):
        if i == j: shp[i][j] = w[i]

shp

array([[-0.01018105,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.49702099,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.34986843,  0.        ],
       [ 0.        ,  0.        ,  0.        , -1.30631738]])

In [138]:
diag_matrix = np.diag(np.random.rand(4))

diag_matrix

array([[0.73827898, 0.        , 0.        , 0.        ],
       [0.        , 0.30722126, 0.        , 0.        ],
       [0.        , 0.        , 0.84671808, 0.        ],
       [0.        , 0.        , 0.        , 0.74504539]])